name: container

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            "ghcr.io/nilic/prometheus-example:${{  github.ref_name }}"
            "ghcr.io/nilic/prometheus-example:latest"
  update-deployment:
    runs-on: ubuntu-20.04
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Update image tag in manifest
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(select(.kind == "Deployment") | .spec.template.spec.containers[] | select(.name == "webapp") | .image) = "ghcr.io/nilic/prometheus-example:${{  github.ref_name }}"' deploy/prometheus-example.yml
      - name: Commit and push changes back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: bump image tag in manifest
